### ISSUE TITLE
elf2e32: Invalid Huffman encoding

### ISSUE THREAD

**Issue by pent0** [fedor4ever/elf2e32#6]
Original elf files and expected results by original tool: https://cdn.discordapp.com/attachments/464664041156116480/536503628547096577/lib.zip

Run options: 
```
E:\Thu\Projects\toolchain\bin\elf2e32 --elfinput="E:/Thu/Projects/toolchain/build/lib/libe32kern.so" --uid1=0x10000079 --uid2=0x10 --uid3=0x80001001 --sid=0x80001001 --version=10.0 --dlldata --output="E:/Thu/Projects/toolchain/build/lib/e32kern.dll" --libpath="E:/Thu/Projects/toolchain/libs" --definput="E:/Thu/Projects/toolchain/libraries/defs/e32kern.def" --defoutput="E:/Thu/Projects/toolchain/build/lib/e32kern.def" --targettype=DLL --dso="E:/Thu/Projects/toolchain/build/lib/libe32kern.a" --linkas="e32kern.dll""
```
Error: 
```
elf2e32 : error : E1022: Invalid Huffman coding during E32Image compression
```

**Comment by fedor4ever** [comment]
I have error too.

**Comment by fedor4ever** [comment]
Crashes even on uncompressed images

**Comment by pent0** [comment]
I will investigate on uncompressed, maybe missing options caused the problem ?

**Comment by fedor4ever** [comment]
@pent0, what compiler options used to build libe32kern.so? -fpic surely broke elf2e32 because that options change internal structure produced elfs.

**Comment by pent0** [comment]
Yes, that's -fpic. But what I found is not really related, because it's checking if dataStart < codeEnd, if it's than the image is not valid. But most of e32 images allow this, dataStart = 0 indicates that there is no data section.

**Comment by pent0** [comment]
![image](https://user-images.githubusercontent.com/25717050/51438951-ca61b400-1ce5-11e9-9fc1-b1d35bc150d3.png)

**Comment by fedor4ever** [comment]
I occasionally found while play with gcc optimisations that -fpic break elf2e32. I read carefully docs:

>>-fPIC
>>Position-independent code requires special support, and therefore works only on certain machines.

>> -fpie
>> -fPIE
>>These options are similar to -fpic and -fPIC, but the generated position-independent code can be only linked into executables. Usually these options are used to compile code that will be linked using the -pie GCC option.

Status: wont fix!

P.S. I will be glad if someone move old hellish code used for e32image generation to E32Producer class =)

**Comment by pent0** [comment]
Here is from my emulator running an executable with data size = 0. Its data offset is also 0 in this case.

![image](https://user-images.githubusercontent.com/25717050/51439068-95eef780-1ce7-11e9-9d6f-7b3ffb46438a.png)

[Executable](https://cdn.discordapp.com/attachments/464664041156116480/536519812138926081/dummyserv.exe)

If data size is not 0, the data offset will not be zero, and will meet your conditional check

![image](https://user-images.githubusercontent.com/25717050/51439084-cb93e080-1ce7-11e9-83d1-4ce76d0700ef.png)

Bounce

I know that i need to remove that -fPIC flag, but your check is doing this to me >_<
And also, i think you are only referring to me, I will take it

**Comment by fedor4ever** [comment]
Ecom plugins usually has data == 0. Misses add to tests AlternateReaderRecog.dll %(

**Comment by pent0** [comment]
I don't understand what you are saying. The check should be strengthen to 

```c++
// Check if data section is present, since elf2e32 sets the dataOffset = 0 if dataSize = 0
// If it's present, dataStart should > codeEnd since right after code section is data section
if (iHdr->iDataSize && (dataStart < codeEnd)
   RETURN_FAILURE(....)
```

**Comment by fedor4ever** [comment]
Bug accepted. It brokes ECOM plugin generation too.

**Comment by pent0** [comment]
Thanks :D

**Comment by fedor4ever** [comment]
Haha =(

Use stable version - https://github.com/fedor4ever/elf2e32/commit/830052db357d2c9bd11a5a5dd29769c83a4ab67d

**Comment by pent0** [comment]
*Don't be sadd ;;;;00*

Right, I will try that.

**Comment by fedor4ever** [comment]
Another mysterious bug :''''''(

**Comment by pent0** [comment]
I can look into it, I already said the problem with uncompressed one, is the data offset is 0 whenever data size = 0 (which it was supposed too, I can point to the place of Symbian source code that takes advantage of that fact). For compressed one, I don't know yet :P

**Comment by fedor4ever** [comment]
for ECOM plugin:

elf2e32 : Error: E1022: Invalid Huffman coding during E32Image compression.

That tool from SDK works ok.

There is only one way - find broken commit and fix it.
For tests run test_exe_options.py and test_dll_options.py. They must not print "Unexpectable test failure: blablabla"!

**Comment by pent0** [comment]
Right than ;0

**Comment by fedor4ever** [comment]
use that commit - 9f2f1d155a7fb549f5b2d62b430d741599293def. It builds compressed exes and dlls(even ECOM). Don't play with options - it works unstable with tricky options.

**Comment by fedor4ever** [comment]
Hell, E32ImportSection *E32Parser::GetImportSection() const trashes E32Validator::ValidateImports() too. Example:

`int32_t E32Validator::ValidateImports() const
{
    if(!iHdr->iImportOffset)
		return KErrNone; // no imports

    // buffer pointer to read relocation from...
    uint8_t* buf = (uint8_t*)iParser->GetBufferedImage();
	uint8_t* bufferEnd = (uint8_t*)(buf + iBufSize); //last byte of E32Image
	printf("E32 Image size: %d", iBufSize);
	uintptr_t d = (uintptr_t)(void *) &bufferEnd;
	printf("\nLast byte addr: %" PRIuPTR "\n", d);

    // read section header (ValidateHeader has alread checked this is OK)...
	E32ImportSection* sectionHeader11 = iParser->GetImportSection();
	E32ImportSection* sectionHeader111 = iParser->GetImportSection();
	E32ImportSection* sectionHeader121 = iParser->GetImportSection();
	E32ImportSection* sectionHeader151 = iParser->GetImportSection();
	E32ImportSection* imports = iParser->GetImportSection();
	uint8_t* sectionStart = (uint8_t*)imports;

	d = (uintptr_t)(void *) &imports;
	printf("sectionHeader2: %" PRIuPTR ", imports->iSize: %d\n", d,
        imports->iSize);`
comment or add new variable sectionHeader** and see how changes"Last byte addr:" value. Value decreases when sectionHeader* removed or increases if new variable added.
@pent0 , any ideas?

**Comment by pent0** [comment]
As I understand, you are outputing the address of pointer to the pointer of bufferEnd, which resides on stack, so any more variable you add makes Last byte addr: change

Just do this:
```c++
uintptr_t d = (uintptr_t)bufferEnd;
```

**Comment by fedor4ever** [comment]
I fix errors  in E32ImageValidaror while E32Image checked.  Compression still broken. I try to recompress: uncompressed-compressed-uncompressed but failed. 
When I rolled that feature compression-decompression work perfectly.

**Comment by pent0** [comment]
Does bytepair broken too? Idk but you can check the diff of the flate file, maybe you change something that broke it. I will try to look into the diff anyway

**Comment by fedor4ever** [comment]
Yes,  bytepair broken too. I fear everything without tests broken.

**Comment by fedor4ever** [comment]
Compression works! For tests I recompress E32Image and file not changed! Test options:

```
 --e32input="tests\AlternateReaderRecogE32.dll" --output="tests\tmp\AlternateReaderRecog.inflate.dll" --compressionmethod=inflate

 --e32input="tests\tmp\AlternateReaderRecog.inflate.dll"  --output="tests\tmp\AlternateReaderRecog.inflate2bytepair.dll" --compressionmethod=bytepair

 --e32input="tests\tmp\AlternateReaderRecog.inflate2bytepair.dll"  --output="tests\tmp\AlternateReaderRecog.decomp.dll" --compressionmethod=none
```
AlternateReaderRecogE32.dll and AlternateReaderRecog.decomp.dll are equal byte by byte. This bug came out from class E32Validator. Just disable ValidateE32Image() call.

Сlass E32Validator too buggy. Can you look for some strange things on it? =)

**Comment by pent0** [comment]
Okay :)

**Comment by fedor4ever** [comment]
@pent0, nothing found?

**Comment by fedor4ever** [comment]
Fixed. E32Validator was not correct. I remove false guards against overflow and underflow heap aviable to app.

**Comment by pent0** [comment]
I was just got home :P Anyway good

**Comment by pent0** [comment]
Is this commit ? 7a39727f0454a4e7fbce1fd4755b93af4da90d4f I don't really see anything solve :P guess i will try and report to you later

**Comment by fedor4ever** [comment]
Okay.

**Comment by pent0** [comment]
Bytepair is still broken, so do defalte :( You pass a null filename to bytepair, so it can't be open and decompress. I will try make bytepair decompression in-memory

**Comment by pent0** [comment]
Actually, I'm gonna keep it safe, write the buffer to a temporary file

**Comment by pent0** [comment]
I don't know if you know or not, but the image wasn't actually compressed when you validate.
It got compress on writing to disk...

The whole decompress thing is unneccessary when you validate. You should move validate to after writing to disk

**Comment by pent0** [comment]
Turns off decompress in E32Parser make elf2e32 works fine, please check

**Comment by fedor4ever** [comment]
Compression and decompression algorythms works fine itself.

> The whole decompress thing is unneccessary when you validate.
Validation starts when E32Image ready to save on disk in two cases:

1. E32Image created from scratch
2. E32Image prepared to compress with another method
In both cases it decomressed already. Anyway my app run much faster than version from SDK.

> Bytepair is still broken, so do defalte :( You pass a null filename to bytepair, so it can't be open and decompress. I will try make bytepair decompression in-memory

I try to compres with bytepair when build DLL from elf and failed...

**Comment by fedor4ever** [comment]
Found more funny thing - when build E32 from elf at validation stage E32Parser tryes to decompress already decompressed image.

**Comment by pent0** [comment]
That's what I was talkinga bout!!!!!!!!!!!!

**Comment by pent0** [comment]
I think you should know your code best ? It will compress when writing to disk

**Comment by pent0** [comment]
When you try to decompress an already decompressed data, it will just garbage and shit itself. There is nothing wrong with the code though, disable this line

https://github.com/fedor4ever/elf2e32/blob/7a39727f0454a4e7fbce1fd4755b93af4da90d4f/source/e32parser.cpp#L95

let me make an e32image well. no error

**Comment by fedor4ever** [comment]
Aha, i know. Is it problem with that storing file?

**Comment by fedor4ever** [comment]
DecompressImage has guard against use for decompressed images

**Comment by pent0** [comment]
Mostly, the only time I see the E32Image got compressed is on this line:
https://github.com/fedor4ever/elf2e32/blob/491b70ade9b05a077bf118ae45e6159ba3ed40c3/source/e32imagefile.cpp#L1169

But it's called after validate

**Comment by fedor4ever** [comment]
But this not work

**Comment by pent0** [comment]
Is there somewhere we can chat :P we are spamming this issue

**Comment by fedor4ever** [comment]
go to steam =)

**Comment by pent0** [comment]
Ok wait

**Comment by fedor4ever** [comment]
Fix pushed!

**Comment by pent0** [comment]
Will report to you later tommorrow, but check out the comments on the commit first

**Comment by fedor4ever** [comment]
close if ok
